### ISSUE TITLE
Serf discover requires a multicast network which is often not avaiable in cloud deployments

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-opendj#19]
[https://github.com/GluuFederation/docker-opendj/blob/4.2/scripts/entrypoint.sh#L31](Current) code uses Serf discover method to find peers. This method lacks support on non-multicast networks. Suggested fix in image is to detect peers and use `serf join <fqdn>` which would cover  multicast and non-multicast networks.

🐛 
This issue has a major impact on scaling as it hinders ldap replication.

**Comment by iromli** [comment]
The image has `GLUU_SERF_MULTICAST_DISCOVER` to toggle support for serf discovery using multicast.
