### ISSUE TITLE
Add script to disable replication

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-opendj#20]
The script can be executed as `preStop` hook.

**Comment by iromli** [comment]
@moabu can you update manifest to include `preStop` hook?

```
preStop:
  exec:
    command: ["python3", "/app/scripts/deregister_peer.py"]
```

**Comment by moabu** [comment]
> 
> 
> @moabu can you update manifest to include `preStop` hook?
> 
> ```
> preStop:
>   exec:
>     command: ["python3", "/app/scripts/deregister_peer.py"]
> ```

Yes as discussed I think this hook will deregister the peer. I'll test on my end
