### ISSUE TITLE
HA setup with serf members

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-opendj#22]
Allow members to be added via file and sync `ldap_peers`. 

In HA setup opendj might be fronted by a NodePort service, and then LB. Talking members should be able to be added via a comma separated or space separated addresses from a file. 
Forexample, we can check a file if mounted `serf_members` and register the addresses there and use those address inside serf.

Example member hosts:

Nodeports:
`opendjeast.example.com:31946`
`opendjwest.example.com:31946`

Currently even if the serf join command is run manually the member is successfully joined but `serf members` gets a different address which is the local internal address and it fails aftwerwards. 

```
/ # serf join opendjeast.example.com.:31946
Successfully joined cluster by contacting 1 nodes.
/ # serf members
gluu-four-ha-opendj-0.opendj.gluu-four-ha.svc.cluster.local            10.233.127.209:7946  alive  role=ldap
gluu-four-ha-west-opendj-0.opendj.gluu-four-ha-west.svc.cluster.local  10.233.72.142:7946   alive  role=ldap
/ # serf members
gluu-four-ha-west-opendj-0.opendj.gluu-four-ha-west.svc.cluster.local  10.233.72.142:7946   failed  role=ldap
gluu-four-ha-opendj-0.opendj.gluu-four-ha.svc.cluster.local            10.233.127.209:7946  alive   role=ldap
```

**Comment by mookkiah** [comment]
Any update on this issue? It is a blocker for setting up HA. @moabu Please confirm this.

**Comment by iromli** [comment]
@mookkiah we are still working on this [branch](https://github.com/GluuFederation/docker-opendj/tree/serf-advertise). While serf membership is fixed, the auto replication of LDAP server still broken.

**Comment by moabu** [comment]
loading an incorrect serf-key from file results in a failure point inside ldap. This should be avoided 

```
INFO - pygluu.containerlib.wait - 2020-12-29 12:55:43,841 - Config is ready
INFO - pygluu.containerlib.wait - 2020-12-29 12:55:43,875 - Secret is ready
INFO - entrypoint - 2020-12-29 12:55:44,646 - Syncing OpenDJ certs.
INFO - entrypoint - 2020-12-29 12:55:44,769 - Checking certificate's Subject Alt Name (SAN)
Traceback (most recent call last):
  File "/app/scripts/entrypoint.py", line 764, in <module>
    main()
  File "/app/scripts/entrypoint.py", line 236, in main
    configure_serf()
  File "/app/scripts/entrypoint.py", line 432, in configure_serf
    "encrypt_key": resolve_serf_key(),
  File "/app/scripts/entrypoint.py", line 407, in resolve_serf_key
    keygen = key_from_file() or key_from_cmd()
  File "/app/scripts/entrypoint.py", line 393, in key_from_file
    keygen = f.read().strip()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 0: invalid start byte

```

**Comment by iromli** [comment]
@moabu how to reproduce this error? How do you generate key?

**Comment by moabu** [comment]
https://github.com/GluuFederation/cloud-native-edition/issues/275
Tutorial created : https://gluu.org/docs/gluu-server/4.2/tutorials/cn-ldap-multi-cluster/

**Comment by iromli** [comment]
Feature added to branch `4.2`.
